---
- name: Deploy Click counter app
  hosts: all
  tasks:
    - name: Create a Docker network
      community.docker.docker_network:
        name: clicknet
        state: present
    
    - name: Run Redis container
      community.docker.docker_container:
        name: redis
        image: redis:alpine
        state: started
        restart_policy: always
        networks:
          - name: clicknet

    - name: Run Click Counter container
      community.docker.docker_container:
        name: clickcounter
        image: kodekloud/click-counter
        state: started
        restart_policy: always
        networks:
          - name: clicknet
        ports:
          - "8085:5000"
